version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.1
    networks:
      - internal-net
    ports:
     - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "localhost: 127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:3.2.1
    networks:
      - internal-net
    ports:
     - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    extra_hosts:
      - "localhost: 127.0.0.1"
  
  spark-master:
    image: bde2020/spark-master:2.2.1-hadoop2.7
    container_name: spark-master
    networks:
      - internal-net
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON=false
  
  spark-worker-1:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    networks:
      - internal-net
    ports:
      - "8081:8081"
    environment:
      - ENABLE_INIT_DAEMON=false

  spark-worker-2:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    networks:
      - internal-net
    ports:
      - "8082:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
  
  spark-worker-3:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: spark-worker-3
    depends_on:
      - spark-master
    networks:
      - internal-net
    ports:
      - "8083:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
  spark-worker-4:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: spark-worker-4
    depends_on:
      - spark-master
    networks:
      - internal-net
    ports:
      - "8084:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
networks:
  internal-net:
    driver: bridge
